### ISSUE TITLE
? Missing Instructions in AWS workshop

### ISSUE THREAD

**Issue by noorjabermd** [aws-samples/aws-iot-robot#54]
Hello. Thanks for providing the tutorial. I didn't see an obvious way to raise questions on AWS so thought I'd ask here. I can't seem to login (Step 7.2, PiBot Provisioning Login) and have worked backwards to try to solve the issue without success. It seems there are some instructions missing at step 6.3 (see image below and 2 arrows). I believe I was able to make the .py scripts executable (chmod +x), but can't confirm and I don't know how to adjust the green grass certificates. Any help would be appreciated.

Thanks,
Noor

<img width="430" alt="AWS_PiBot_login" src="https://github.com/aws-samples/aws-iot-robot/assets/153292286/bbd8902f-a619-4dd9-b072-85347b4d6f16">

<img width="1542" alt="AWS_PiBot" src="https://github.com/aws-samples/aws-iot-robot/assets/153292286/f20e65b3-550e-43b7-b0d8-167879dc8b24">

**Comment by gemmerton** [comment]
Thanks for pointing out the problem.  I will have a look and update the instructions in the workshop.  

The command to do this is: `chmod +x filename.py`

and you'll need to run that for each of the 4 files in the directory.

I am in the process of doing some updates to the workshop hopefully early new year and it is likely that I'll recommend using the 'provision one core device' from the console as the default option and have the trusted user provisioning as a secondary option for those specifically interested on how that piece works, as it is a lot of work for provisioning a single device

**Comment by noorjabermd** [comment]
Thanks @gemmerton. I'm running through the tutorial again after a fresh raspbian installation and have been taking notes. I'll  get back to you soon with issues I had along the way to help with your update.

**Comment by noorjabermd** [comment]
Some of the issues I was running into stemmed, I believe, from using the 64-bit Bookworm instead of 32-bit bullseye.  I used 32-bit Bookworm and Amazon Linux 2 as done in the tutorial and ran through the steps again. I've documented the issues this time around. Will raise the issues separately.

To answer your question above, the commands prior to the logon instructions in section 7 worked successfully and I was able to see the user populate in the provisioning-user pool as well. I tried again this time around and had the same issue so I set up one core device instead and moved on.

**Comment by gemmerton** [comment]
I've removed the Trusted User Provisioning part from the workshop for now (pending publication) - will add in back later if/when I can simplify.

I'm also adding a note in the introduction section that this has been tested on Bullseye only, and I'll update this when I manage to do a full test on Bookworm

**Comment by gemmerton** [comment]
Hi Noor, is anything else needed on this issue or are you happy to close?

**Comment by noorjabermd** [comment]
Happy to close. Thanks again
