### ISSUE TITLE
Step 8 issue

### ISSUE THREAD

**Issue by noorjabermd** [aws-samples/aws-iot-robot#57]
Step 8.7
running "make" fails on both 32-bit bullseye and 64-bit Bookworm: 

I kept running into errors with openssl but was able to successfully build after modifying CMakelists.txt. See: https://github.com/dave-malone/aws-kvs-webrtc-demo-for-raspberry-pi/blob/main/build-kvs-webrtc.sh. I entered these lines in the terminal after running "cmake ..".

# patch CMakeLists.txt; don't build openssl or mbedtls since those are installed via package manager
sed -i 's+build_dependency(openssl ${BUILD_ARGS})+#build_dependency(openssl ${BUILD_ARGS})+g' amazon-kinesis-video-streams-webrtc-sdk-c/CMakeLists.txt
sed -i 's+set(OPENSSL_ROOT_DIR ${OPEN_SRC_INSTALL_PREFIX})+#set(OPENSSL_ROOT_DIR ${OPEN_SRC_INSTALL_PREFIX})+g' amazon-kinesis-video-streams-webrtc-sdk-c/CMakeLists.txt
sed -i 's+build_dependency(mbedtls ${BUILD_ARGS})+#build_dependency(mbedtls ${BUILD_ARGS})+g' amazon-kinesis-video-streams-webrtc-sdk-c/CMakeLists.txt

Thanks,
Noor

**Comment by gemmerton** [comment]
Hi Noor,

I'm checking with the author (Dave Malone) regarding the update you identified and will update accordingly the instructions once confirmed.

**Comment by gemmerton** [comment]
I've checked with the KVS team and these lines should not be required any more, however I want to run a test myself to check first.  In the meantime I've added the commands to the workshop with a note to run them if errors occur in the build

**Comment by noorjabermd** [comment]
Great. Thanks
