### ISSUE TITLE
Step 13 Issue

### ISSUE THREAD

**Issue by noorjabermd** [aws-samples/aws-iot-robot#60]
Step 13.1
Site access error
When navigating to the cloudfront website, I kept getting access denied error. I double-checked the S3 bucket settings and troubleshooted [here](https://repost.aws/knowledge-center/s3-website-cloudfront-error-403) with no obvious reason as to why I was getting the error. Input would be appreciated.

Thanks,
Noor

**Comment by gemmerton** [comment]
Hi Noor,
I think I've found the problem, and will update the workshop to cover this.  You'll need to edit the origin in your CloudFront distribution to add the region to the origin domain.  For example:

change: 
my-robot-bucket.s3.amazonaws.com

to:
my-robot-bucket.s3.eu-west-1.amazonaws.com

obviously make sure the region you add is the region in which your S3 bucket exists.  Also make sure that when you change the origin domain, re-check that the Origin Access Identity is set correctly - I've seen this reset/clear when you change the domain so re-select if required.  Select "Legacy access identities" and the appropriate Origin access identity from the drop-down.

I will update this to use the more recent origin access control settings in a future release.

**Comment by noorjabermd** [comment]
Thanks @gemmerton. That fixed the issue. 
I'm now able to login and can select my device from the top left and I see MQTT is connected. Looking at the console, when I click "Connect to the WebRTC Stream" it seems to hang at "Generating ICE Candidates" as VIEWER with no output on the page. I can confirm video from the Pi can be viewed on the AWS KVS dashboard as well as the KVS WebRTC test page. Any ideas?

**Comment by gemmerton** [comment]
Hi Noor,

First check is to confirm that the KVS signalling channel has the same name as the IoT Thing/Greengrass Core of the robot.  Have a look at the monitoring tab on the KVS console and you'll be able to see connection attempts by the master and the viewer.  As you're seeing video in the console you will see connections from the master (robot) and just need to see if viewer connections from the web app are also being seen.

I have seen on occassion what you are experiencing and in a lot of cases it has resolved itself by a reboot of the Pi (sorry, I always feel bad suggesting a reboot :-) )

**Comment by noorjabermd** [comment]
Thanks @gemmerton.
Ha! No worries. I've rebooted without any change. Not sure why, but the Pibot Site's video stream will not load on Safari even though the WebRTC test page works fine (on Safari). I switched to chrome and I'm now able to see the video stream on the Pibot site. Thanks for all of your help and the tutorial.

**Comment by gemmerton** [comment]
Hi Noor, are you okay to close this issue?

**Comment by noorjabermd** [comment]
Happy to close. Thanks
